typography_spectrum: 0.015611948445439339
color:
  brandStrength: 0.5776637773960829
  lightness: 0.06945464643649757
  saturation: 0.21169270551763475
  rhythmicContrast: 0.7029214166104794
  brandColors:
    - '#1C1D21'
    - '#31353D'
    - '#445878'
    - '#92CDCF'
    - '#EEEFF7'
layout_spectrum: 0.48712387355044484
author:
  name: Aristotelous Dimitris
  email: dimitri.aristotelous@gmail.com
  url: dimitrisaristotelous.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/88782fad-7b5c-4c80-924d-e399ed6cc62d.png
name: Wedding Photography Cyprus
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a3206251-5fa7-4df6-9265-ccb34a86d55c.png
